# Generated by Django 2.2.5 on 2019-10-20 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_deal_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 15, 1, 45, 53581)),
        ),
    ]
